[general]
problem = "Burgers"
outputDir = "."

[mesh]
Dimension = 1
NumberOfCells = NCELLS
a = 0
b = 3

[problem]
timestepping = "TIMESTEPPING"
CFL = CFLNUM
limiter = "minmod"
tEnd = 0.14
nStates = 1
variance = VAR

[moment_system]
closure = "CLOSURE"
moments = MOMENTS
quadType = "legendre"
quadPoints = QUADPTS
maxIterations = 200
epsilon = 5e-5

[plot]
engine = "matplotlib"
cellIndex = 110
evalPoints = 1000
