[general]
problem = "Burgers"
outputFolder = "results"

[mesh]
Dimension = 1
NumberOfCells = 80 
a = 0
b = 3

[problem]
CFL = 0.25
limiter = "none"
tEnd = 0.14

[moment_system]
moments = 3
quadType = "legendre"
quadPoints = 100
maxIterations = 1000
epsilon = 5e-5
