[general]
problem = "Euler2D"
outputDir = "../results"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "naca0012.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "euler_naca0012"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = "Hermite"
CFL = 0.042
tEnd = 0.1

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D
closure = "Euler2D"
moments = 5
quadPoints = 15
maxIterations = 100
epsilon = 5e-5
