[general]
problem = "Euler1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 2000
a = 0
b = 1
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.01]]
CFL = 0.75
tEnd = 0.1

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter
closure = "Euler"
moments = [["maxDegree"],[5]]
quadPoints = [["tensorizedGrid"],[10]]
regularizationStrength = 0.0001
# quadPoints = [["tensorizedGrid"],[ 7 ]]
maxIterations = 10000
epsilon = 1e-9
