[general]
problem = "Euler1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 500
a = 0
b = 1
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre","Legendre","Legendre"],[0.02,0.05,0.05]]
CFL = 0.9
tEnd = 0.2

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter
closure = "Euler"
moments = [["totalDegree"],[5]]
quadPoints = 10
maxIterations = 200
epsilon = 5e-5
