[general]
problem = "Burgers"
outputFolder = "results"

[mesh]
Dimension = 1
NumberOfCells = 320
a = 0
b = 3

[problem]
CFL = 0.9
limiter = "none"
tEnd = 0.14

[moment_system]
moments = 5
quadType = "legendre"
quadPoints = 40
maxIterations = 200
epsilon = 1e-6

[plot]
cellIndex = 220
evalPoints = 1000
