[general]
problem = "Burgers"
outputDir = "results"

[mesh]
Dimension = 1
NumberOfCells = 164
a = 0
b = 3

[problem]
# available timesteppings: explicitEuler, Heun, SSPMultiStep
timestepping = "explicitEuler"
CFL = 0.5
# available limiter: minmod, none|off
limiter = "none"
tEnd = 0.14
nStates = 1

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin
closure = "BoundedBarrier"
moments = 15
quadType = "legendre"
quadPoints = 50
maxIterations = 200
epsilon = 5e-5

[plot]
cellIndex = 110
evalPoints = 1000
