[general]
problem = "Euler2D"
outputDir = "../results"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "naca0012.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "eulerNaca0012pSC"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0005]]
#distribution = [["Legendre"],[0.0]]
CFL = 0.5
tEnd = 0.1
residual = 1e-10

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, HyperbolicityLimiter
closure = "StochasticGalerkin"
moments = [["totalDegree"],[5]]
#moments = [["totalDegree"],[9]]
quadPoints = [["tensorizedGrid"],[6]]
#quadPoints = [["tensorizedCCGrid"],[4]]
#refinementThresholds = [0.0002, 0.00002]
#regularizationStrength = 0.01
maxIterations = 10000
epsilon = 5e-5
