[general]
problem = "Euler1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 1000
a = 0
b = 1
outputFile = "N6Nq20sod_IPMLambda5e-6Eta1e-5FullVarianceFull"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.05]]
CFL = 0.5
tEnd = 0.14

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler, RegularizedExpEuler, RegularizedLassoEuler
closure = "RegularizedEuler"
moments = 6
quadPoints = 20
maxIterations = 2000
epsilon = 1e-5
filterStrength = 5e-6
regularizationStrength = 1e-5
