[general]
problem = "Euler1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 1000
a = 0
b = 1
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.05]]
CFL = 0.5
tEnd = 0.14

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler, RegularizedExpEuler
closure = "RegularizedExpEuler"
moments = 5
quadPoints = 20
maxIterations = 2000
epsilon = 1e-5
filterStrength = 0.00005
regularizationStrength = 1e-6#1e-5
