[general]
problem = "Euler2D"
outputDir = "../results"
restartFile = "../../result_sync/plots/l1_error_box_new/logs/2019-04-16_20:23:24"
referenceSolution = "../../result_sync/SC/unknown/euler2D_nacaCoarse_sc_n100_s05_aoa_r1e-06/euler2D_nacaCoarse_sc_n100_s05_aoa_r1e-06.vtk"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "nacaCoarse.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "foo"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.5]]
CFL = 0.9
tEnd = 200.0
residual = 1e-6

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "Euler2D"
moments = [["totalDegree"],[5]]
quadPoints = 10
maxIterations = 1
epsilon = 1e-7
