[general]
problem = "Burgers"
outputFolder = "results"

[mesh]
dimension = 1
xCells = 10

[problem]
CFL = 0.9
limiter = "none"
tEnd = 1

[moment_system]
moments = 1
quadType = "legendre"
quadPoints = 1
