[general]
problem = "Euler2D"
outputDir = "../results"
restartFile = "../input/2019-04-16_20:42:19"
referenceSolution = "../../result_sync/SC/unknown/euler2D_nacaCoarse_sc_n100_s05_aoa_r1e-06/euler2D_nacaCoarse_sc_n100_s05_aoa_r1e-06.vtk"
importDualState = true

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "nacaCoarse.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "regularizedEuler"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.5]]
CFL = 0.9
tEnd = 1000.0
residual = 1e-6

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler
closure = "RegularizedEuler"
moments = 5
quadPoints = 15
maxIterations = 1000
epsilon = 1e-7
filterStrength = 5e-6
regularizationStrength = 1e-5
