[general]
problem = "Euler2D"
outputDir = "../results"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "pipe.su2"
SU2BC = [["inlet","dirichlet"],["outlet","dirichlet"], ["walls", "noslip"]]
outputFile = "pipeNewL2Lambda0-0000015"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre","Legendre","Legendre"],[0.1,0.05,0.05]]
CFL = 0.9
tEnd = 0.0035
residual = 1e-6

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler
closure = "StochasticGalerkin"
moments = [["totalDegree"],[5]]
quadPoints = [["sparseGrid"],[6]]
maxIterations = 1000
epsilon = 1e-7
