[general]
problem = "Burgers1D"
outputDir = "results"

[mesh]
dimension = 1
numberOfCells = 100
a = 0
b = 3
outputFile = "burgers_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
CFL = 0.5
# available limiter: minmod, none|off
limiter = "none"
tEnd = 0.14

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler
closure = "BoundedBarrier"
moments = 3
quadPoints = 10
maxIterations = 200
epsilon = 5e-5

[plot]
enabled = true
steps = 5
time  = 0.01
