[general]
problem = "Euler1D"
outputDir = "../results"
writeFrequency = 10

[mesh]
dimension = 1
numberOfCells = 2000
a = 0
b = 1
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0]]
CFL = 0.75
tEnd = 0.23

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter
closure = "Euler"
moments = [["maxDegree"],[0]]
quadPoints = [["tensorizedGrid"],[2]]
# quadPoints = [["tensorizedGrid"],[ 7 ]]
maxIterations = 200
epsilon = 5e-5
