[general]
problem = "PNEquations"
outputDir = "../results"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "square.su2"
SU2BC = [["OuterBoundary","dirichlet"]]
outputFile = "pnTestKerstin"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0]]
CFL = 0.9 # 0.1
tEnd = 0.75
residual = -1.0
nPNMoments = 5

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler
closure = "StochasticGalerkin"
moments = [["totalDegree"],[1]]
quadPoints = [["tensorizedGrid"],[2]]
maxIterations = 1000
epsilon = 1e-7
