[general]
# avaiable problems: Burgers, Euler
problem = "Euler"
outputDir = "results"

[mesh]
Dimension = 2
SU2File = "../input/naca0012.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "../results/euler_naca0012.vtu"

[problem]
# available timesteppings: explicitEuler, Heun, SSPMultiStep
timestepping = "explicitEuler"
CFL = 5.0
# available limiter: minmod, none|off
limiter = "none"
tEnd = 0.14

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler
closure = "Euler"
moments = 15
quadType = "legendre"
quadPoints = 50
maxIterations = 200
epsilon = 5e-5

[plot]
cellIndex = 10
evalPoints = 1000
