[general]
problem = "Burgers1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 2000
a = 0
b = 3
outputFile = "burgers_shock_tStar_LB"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.2]]
CFL = 0.95
tEnd = 0.0909

[moment_system]
# available closures: BoundedBarrier,LogBarrier, LogSin, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "LogBarrier"
moments = [["totalDegree"],[5]]
quadPoints = [["tensorizedGrid"],[10]]
maxIterations = 2000
epsilon = 1e-7
