[general]
problem = "Euler2D"
outputDir = "../results"
writeFrequency = 2
referenceSolution = "sc50UncertainMaSigma0-025PSigma1000-0Dim2.vtk"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "nacaCoarse.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "pSC5_2d"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre","Legendre"],[0.025,1000.0]]
CFL = 0.9
tEnd = 100.0
residual = 1e-8

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "StochasticGalerkin"
moments = [["maxDegree"],[4]]
quadPoints = [["tensorizedCCGrid"],[2]]
maxIterations = 10
epsilon = 1e-7
