[general]
problem = "Euler1D"
outputDir = "../results"
writeFrequency = 10

[mesh]
dimension = 1
numberOfCells = 100
a = 0
b = 1
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.05]]
CFL = 0.5
tEnd = 0.23

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter
closure = "StochasticGalerkin"
moments = [["totalDegree"],[3]]
quadPoints = [["tensorizedGrid"],[6]]
# quadPoints = [["tensorizedGrid"],[ 7 ]]
maxIterations = 200
epsilon = 5e-5
