[general]
problem = "Euler2D"
outputDir = "../results/nozzleFlux"
writeFrequency = 2

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "nozzleCoarse.su2"
SU2BC = [["outlet","dirichlet"], ["walls", "noslip"]]
outputFile = "nozzle"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0]]
CFL = 0.9
tEnd = 0.2 #0.0035

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "StochasticGalerkin"
moments = [["totalDegree"],[1]]
quadPoints = [["tensorizedGrid"],[3]]
#filterStrength = 0.000002
#regularizationStrength = 1e-4
maxIterations = 1000
epsilon = 1e-7
