[general]
problem = "Euler1D"
outputDir = "results"

[mesh]
dimension = 1
numberOfCells = 500
a = 0
b = 1
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler, Heun, SSPMultiStep
timestepping = "explicitEuler"
CFL = 5.0
# available limiter: minmod, none|off
limiter = "none"
tEnd = 0.14

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler
closure = "Euler"
moments = 5
quadPoints = 50
maxIterations = 200
epsilon = 5e-5

[plot]
enabled = true
steps = 10
time = 0.01
