[general]
problem = "Euler1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 1000
a = 0
b = 1
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.075]]
CFL = 0.9
tEnd = 0.2

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler
closure = "RegularizedEuler"
moments = 5
quadPoints = 10
maxIterations = 2000
epsilon = 5e-5
filterStrength = 0.00002
regularizationStrength = 1e-4#1e-5
