[general]
problem = "Euler1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 2000
a = 0
b = 1
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.05]]
CFL = 0.75
tEnd = 0.14

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter
closure = "Euler"
moments = [["totalDegree"],[4]]
quadPoints = [["tensorizedCCGrid"],[4]]
refinementThresholds = [0.0001, 0.00001]
regularizationStrength = 0.0
filterStrength = 0.0
maxIterations = 10000
epsilon = 1e-5
