[general]
problem = "Euler1D"
outputDir = "../results/PaperLouisa"
#writeFrequency = 2

[mesh]
dimension = 1
numberOfCells = 2000
a = 0.0
b = 1.0
outputFile = "sod_fIPMN14Nq30Nx2000IPMFokkerPlanck5e-5"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.05]]
CFL = 0.75
tEnd = 0.14

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, HyperbolicityLimiter, ExponentialFilter, SplineFilter, HouLiFilter
closure = "Euler"
moments = [["totalDegree"],[14]]
quadPoints = [["tensorizedGrid"],[30]]
#quadPoints = [["tensorizedCCGrid"],[2, 3, 3, 3, 4]]
nMultiElements = 1
#refinementThresholds = [0.005, 0.0005]
regularizationStrength = 1e-7
filterStrength = 5e-5
filter = "FokkerPlanck"
maxIterations = 10000
epsilon = 1e-7
