[general]
problem = "Burgers"
outputFolder = "results"

[mesh]
Dimension = 1
NumberOfCells = 156
a = 0
b = 3

[problem]
CFL = 0.99
limiter = "none"
tEnd = 0.14

[moment_system]
moments = 5
quadType = "legendre"
quadPoints = 30
maxIterations = 200
epsilon = 5e-5

[plot]
cellIndex = 110
evalPoints = 1000
