[general]
problem = "Euler2D"
outputDir = "../results"
#restartFile = "../results/logs/2019-02-16_13:56:15"
#importDualState = true
#icFile = "../../su2/SU2RefSol.vtk"
#referenceSolution = "../results/collNaca_n20_nq20_s125_reference.vtk"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "nacaCoarse.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "euler_naca0012"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[1.25]]
CFL = 0.9
tEnd = 0.01

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "Euler2D"
moments = 5
quadPoints = 10
maxIterations = 1
epsilon = 5e-5

