[general]
problem = "Euler2D"
outputDir = "../results"
#icFile = "../../su2/SU2RefSol.vtk"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "nacaCoarse.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "euler_naca0012_Collocation_Nq5_Sigma0-5"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.5]]
CFL = 0.9
tEnd = 0.201
residual = 2.2e-3

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "StochasticGalerkin"
moments = 5
quadPoints = 5
maxIterations = 1
epsilon = 5e-5

