[general]
problem = "Burgers"
outputDir = "results"

[mesh]
Dimension = 1
NumberOfCells = 156
a = 0
b = 3

[problem]
CFL = 0.5
timestepping = "explicitEuler"
limiter = "minmod"
tEnd = 0.14
nStates = 1

[moment_system]
moments = 15
quadType = "legendre"
quadPoints = 30
maxIterations = 200
epsilon = 5e-5

[plot]
engine = "gnuplot"
cellIndex = 110
evalPoints = 1000
