[general]
# avaiable problems: Burgers, Euler, Euler2D
problem = "Euler2D"
outputDir = "results"

[mesh]
Dimension = 2
SU2File = "../input/naca0012.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "../results/euler_naca0012.vtu"

[problem]
# available timesteppings: explicitEuler, Heun, SSPMultiStep
timestepping = "explicitEuler"
CFL = 100.0
# available limiter: minmod, none|off
limiter = "none"
tEnd = 1.0

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D
closure = "Euler2D"
moments = 1
quadType = "legendre"
quadPoints = 2
maxIterations = 200
epsilon = 5e-5

[plot]
cellIndex = 10
evalPoints = 1000
