[general]
problem = "Euler2D"
outputDir = "../results"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "pipe.su2"
SU2BC = [["inlet","dirichlet"],["outlet","dirichlet"], ["walls", "noslip"]]
outputFile = "pipeCriticalSettingSigma0-2IPMRegularizedLambda2e-6Gamma1e-5N6"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.2]]
CFL = 0.9
tEnd = 0.005
residual = 0.0

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler, RegularizedLassoEuler
closure = "RegularizedEuler"
moments = 6
quadPoints = 20
maxIterations = 10000
epsilon = 1e-7
filterStrength = 2e-6
regularizationStrength = 1e-5
