[general]
problem = "Euler1D"
outputDir = "../results"
#writeFrequency = 2

[mesh]
dimension = 1
numberOfCells = 1000
a = 0.0
b = 1.0
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.1]]
CFL = 0.75
tEnd = 0.25

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, HyperbolicityLimiter
closure = "HyperbolicityLimiter"
moments = [["totalDegree"],[10]]
quadPoints = [["tensorizedGrid"],[20]]
#refinementThresholds = [0.0001, 0.00001]
#regularizationStrength = 1e-7
filterStrength = 1e-6
maxIterations = 10000
epsilon = 1e-7
