[general]
problem = "NavierStokes"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 100
a = 0.0
b = 1.0
outputFile = "navier_stokes_out"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0]]
CFL = 0.1
tEnd = 0.1
gamma = 1.4
mu = 0.001

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter
closure = "StochasticGalerkin"
moments = [["totalDegree"],[1]]
quadPoints = [["tensorizedGrid"],[2]]
#refinementThresholds = [0.0001, 0.00001]
#regularizationStrength = 1e-5
maxIterations = 10000
epsilon = 1e-5
