[general]
problem = "Euler1D"
outputDir = "../results"
writeFrequency = 50

[mesh]
dimension = 1
numberOfCells = 500
a = 0
b = 1
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre","Legendre"],[0.05,0.05]]
CFL = 0.75
tEnd = 0.14

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter
closure = "StochasticGalerkin"
moments = [["maxDegree"],[8]]
quadPoints = [["tensorizedCCGrid"],[3]]
#refinementThresholds = [0.0001, 0.00001]
#regularizationStrength = 0.0
#filterStrength = 0.0
maxIterations = 10000
epsilon = 1e-5
