[general]
problem = "Burgers1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 500
a = 0
b = 3
outputFile = "burgers_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.5]]
CFL = 0.75
tEnd = 0.12

[moment_system]
# available closures: BoundedBarrier, LogSin, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedBoundedBarrier
closure = "RegularizedBoundedBarrier"
moments = 5
quadPoints = 10
maxIterations = 2000
epsilon = 5e-5
filterStrength = 0.0002
regularizationStrength = 1e-4
