[general]
problem = "Euler1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 5000
a = 0.2
b = 0.9
outputFile = "euler_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.05]]
CFL = 0.9
tEnd = 0.14

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter
closure = "Euler"
moments = [["totalDegree"],[6]]
quadPoints = [["tensorizedGrid"],[30]]
#refinementThresholds = [0.0001, 0.00001]
#regularizationStrength = 1e-7
#filterStrength = 5e-7#7.5e-7
maxIterations = 10000
epsilon = 1e-7
