[general]
problem = "Euler2D"
outputDir = "../results"
restartFile = "../results/logs/2019-02-16_13:56:15"
#icFile = "../../su2/SU2RefSol.vtk"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "naca0012.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "euler_naca0012"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.75]]
CFL = 0.9
tEnd = 0.00001

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "StochasticGalerkin"
moments = 1
quadPoints = 1
maxIterations = 1
epsilon = 5e-5

