[general]
problem = "Burgers1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 1000
a = 0
b = 3
outputFile = "burgers_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.01]]
CFL = 0.9
tEnd = 0.14

[moment_system]
# available closures: BoundedBarrier, LogSin, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "StochasticGalerkin"
moments = [["totalDegree"],[5]]
quadPoints = [["tensorizedGrid"],[10]]
maxIterations = 2000
epsilon = 5e-5
