[general]
problem = "Euler2D"
outputDir = "../results"
writeFrequency = 50
restartFile = "2019-07-16_16:04:28"
referenceSolution = "sc100.vtk"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "nacaCoarse.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "restartEuler"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.5]]
CFL = 0.9
tEnd = 1000.0
residual = 1e-6

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "Euler2D"
moments = [["totalDegree"],[9]]
quadPoints = [["sparseGrid"],[4]]
#cRetardation = [[1,2,4],[0.01,0.005,0.001]]
#refinementThresholds = [0.0001, 0.00001]
maxIterations = 1000
epsilon = 1e-7
