[general]
# avaiable problems: Burgers, Euler
problem = "Burgers"
outputDir = "results"

[mesh]
Dimension = 1
NumberOfCells = 100
a = 0
b = 3

[problem]
# available timesteppings: explicitEuler, Heun, SSPMultiStep
timestepping = "explicitEuler"
CFL = 0.5
# available limiter: minmod, none|off
limiter = "none"
tEnd = 0.14

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler
closure = "BoundedBarrier"
moments = 3
quadType = "legendre"
quadPoints = 10
maxIterations = 200
epsilon = 5e-5

[plot]
cellIndex = 10
evalPoints = 1000
