[general]
problem = "Euler2D"
outputDir = "../results"
#restartFile = "../../result_sync/CAOS-IPM/euler2D_nacaCoarse_caosipm_n10_nq15_s05_aoa/2019-03-01_15:37:33"
#restartFile = "../../result_sync/CA-IPM/euler2D_nacaCoarse_caipm_n10_nq15_s05_aoa/2019-03-01_15:37:27"
#restartFile = "../../result_sync/SC/euler2D_nacaCoarse_sc_n50_s05_aoa/2019-02-25_19:21:59"
#restartFile = "../../result_sync/SC/euler2D_nacaCoarse_sc_n5_s05_aoa/2019-02-28_14:35:30"
restartFile = "../../result_sync/IPM/euler2D_nacaCoarse_ipm_n5_nq10_s05_aoa/2019-02-27_19:17:04"

#restartFile = "../results/logs/2019-03-06_16:19:03"
#importDualState = true
#restartFile = "../../result_sync/SC/euler2D_nacaCoarse_sc_n5_s05_aoa/2019-02-28_14:35:30"
referenceSolution = "../results/euler2D_nacaCoarse_sc_n50_s05_aoa_restart.vtk"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "nacaCoarse.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "errorRestartIPM5Moments"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.5]]
CFL = 0.9
tEnd = 2.0
residual = 1e-6

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "Euler2D"
moments = 5
quadPoints = 10
maxIterations = 1000
epsilon = 1e-7

