[general]
problem = "Euler2D"
outputDir = "../results"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "naca0012.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "euler_naca0012"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
CFL = 0.04
tEnd = 0.001

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D
closure = "StochasticGalerkin"
moments = 1
quadPoints = 1
maxIterations = 200
epsilon = 5e-5

[plot]
enabled = false
