[general]
problem = "Euler"
outputDir = "results"

[mesh]
Dimension = 1
NumberOfCells = 1000
a = 0
b = 1

[problem]
# available timesteppings: explicitEuler, Heun, SSPMultiStep
timestepping = "explicitEuler"
CFL = 5.0
# available limiter: minmod, none|off
limiter = "none"
tEnd = 0.14
nStates = 3

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler
closure = "Euler"
moments = 5
quadType = "legendre"
quadPoints = 50
maxIterations = 200
epsilon = 5e-5

[plot]
cellIndex = 110
evalPoints = 1000
