[general]
problem = "Burgers1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 500
a = 0
b = 3
outputFile = "burgers_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre","Legendre"],[0.1, 0.7]]
CFL = 0.9
tEnd = 0.12

[moment_system]
# available closures: BoundedBarrier, LogSin, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "StochasticGalerkin"
moments = [["maxDegree"],[4]]
quadPoints = [["tensorizedCCGrid"],[2]]
maxIterations = 2000
epsilon = 5e-5
