[general]
problem = "Euler2D"
outputDir = "../results/nozzle"
#writeFrequency = 10

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "nozzleCoarse.su2"
SU2BC = [["outlet","dirichlet"], ["walls", "noslip"]]
outputFile = "nozzleIPMFP"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.5]]
CFL = 0.7
tEnd = 4.0 #0.0035

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "Euler2D"
moments = [["totalDegree"],[5]]
quadPoints = [["tensorizedGrid"],[10]]
filterStrength = 0.00001
#regularizationStrength = 1e-4
maxIterations = 1000
epsilon = 1e-7
