[general]
problem = "Euler1D"
outputDir = "../results"
#writeFrequency = 2

[mesh]
dimension = 1
numberOfCells = 1000
a = 0.0
b = 1.0
#outputFile = "euler_shock_filter0-75order15_P5_"
outputFile = "euler_shock_no_MPI_P5_"
#outputFile = "euler_shock_fSG_P4_ME4"
#outputFile = "euler_shock_SG_P21"
#outputFile = "euler_shock_SG_P4_ME4"
#outputFile = "euler_shock_ref_"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.1]]
CFL = 0.75
tEnd = 0.21

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, HyperbolicityLimiter, ExponentialFilter, SplineFilter, HouLiFilter
closure = "StochasticGalerkin"
moments = [["totalDegree"],[5]]
quadPoints = [["tensorizedGrid"],[10]]
nMultiElements = 4
#refinementThresholds = [0.0001, 0.00001]
#regularizationStrength = 1e-7
#filterStrength = 1.0
#filterOrder = 7
maxIterations = 10000
epsilon = 1e-7
