[general]
problem = "Burgers1D"
outputDir = "../results"

[mesh]
dimension = 1
numberOfCells = 1500
a = 0
b = 3
outputFile = "burgers_shock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = ["Legendre"]
CFL = 0.75
tEnd = 0.12

[moment_system]
# available closures: BoundedBarrier, StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter
closure = "BoundedBarrier"
moments = 10
quadPoints = 40
maxIterations = 2000
epsilon = 5e-5
