[general]
problem = "M1Equations"#"PNEquations"#"M1Equations"
outputDir = "../results"
#writeFrequency = 100
#restartFile = "../input/restart_rad_hydro_Ma4"

[mesh]
dimension = 1
numberOfCells = 500
a = -0.75
b = 0.75
outputFile = "M1"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0]]
CFL = 0.75 # 0.1
tEnd = 0.5

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler, RadiationHydrodynamics, M1
closure = "StochasticGalerkin"
moments = [["maxDegree"],[1]]
quadPoints = [["tensorizedGrid"],[2]]
#filterStrength = 0.001
maxIterations = 1000
epsilon = 1e-3

