[general]
problem = "Euler2D"
outputDir = "../results"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "nacaCoarse.su2"
SU2BC = [["farfield","dirichlet"], ["airfoil", "noslip"]]
outputFile = "euler2D_naca0012_n10_nq15_s05_aoa"

[problem]
timestepping = "explicitEuler"
distribution = [["Legendre"],[0.5]]
CFL = 0.9
tEnd = 0.2

[moment_system]
closure = "Euler2D"
moments = 10
quadPoints = 15
maxIterations = 1
epsilon = 5e-5
