[general]
problem = "RadiationHydrodynamics"
outputDir = "../results"
writeFrequency = 1000
restartFile = "../input/restart_rad_hydro_Ma4"

[mesh]
dimension = 1
numberOfCells = 1000
a = -1
b = 1
outputFile = "RadiationHydrodynamics_1D_new"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0]]
CFL = 0.22 # 0.1
tEnd = 0.035

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler
closure = "StochasticGalerkin"
moments = [["totalDegree"],[0]]
quadPoints = [["tensorizedGrid"],[1]]
maxIterations = 1000
epsilon = 1e-7
