[general]
problem = "ThermalPN"
outputDir = "../results"
writeFrequency = 100000
#restartFile = "../input/restart_rad_hydro_Ma4"

[mesh]
dimension = 2
format = "SU2"
SU2MeshFile = "squareThermalRadLambda15-53.su2"
SU2BC = [["OuterBoundary","dirichlet"]]
outputFile = "ThermalRadiative"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0]]
CFL = 1.0
#tEnd = 0.3
tEnd = 1.7987547480000001
# tEnd = 0.06 * 1e-9 * 299792458.0 * 100.0 
nPNMoments = 1

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler, RadiationHydrodynamics, M1, ThermalRadiation
closure = "StochasticGalerkin"
moments = [["totalDegree"],[1]]
quadPoints = [["tensorizedGrid"],[1]]
#refinementThresholds = [0.1,0.001]
maxIterations = 1
epsilon = 1e-7
