[general]
problem = "ThermalPN"
outputDir = "../results/thermal/gif"
writeFrequency = 100
#restartFile = "../input/restart_rad_hydro_Ma4"

[mesh]
dimension = 1
numberOfCells = 5000
a = -4.0
b = 4.0
outputFile = "ThermalRadiativeTransferRadiatingShock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0]]
CFL = 0.6# 0.1
tEnd = 1.5
nPNMoments = 1

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler, RadiationHydrodynamics, M1, ThermalRadiation
closure = "StochasticGalerkin"
moments = [["totalDegree"],[1]]
quadPoints = [["tensorizedGrid"],[1]]
#refinementThresholds = [0.1,0.001]
maxIterations = 1
epsilon = 1e-7
