[general]
problem = "ThermalPN"
outputDir = "../results/thermal/gif"
writeFrequency = 10000
#restartFile = "../input/restart_rad_hydro_Ma4"

[mesh]
dimension = 1
numberOfCells = 200
a = 0.0
#b = 0.025
b = 2.6997840172786187
outputFile = "ThermalRadiativeTransferRadiatingShock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0]]
CFL = 0.1# 0.1
tEnd = 1446.0
#tEnd = 156155.50755939528
nPNMoments = 1

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler, RadiationHydrodynamics, M1, ThermalRadiation
closure = "StochasticGalerkin"
moments = [["totalDegree"],[1]]
quadPoints = [["tensorizedGrid"],[2]]
#refinementThresholds = [0.1,0.001]
maxIterations = 1
epsilon = 1e-7
