[general]
problem = "ThermalPN"
outputDir = "../results/thermal/gif"
writeFrequency = 50
#restartFile = "../input/restart_rad_hydro_Ma4"

[mesh]
dimension = 1
numberOfCells = 1000
a = -4.0
b = 4.0
outputFile = "ThermalRadiativeTransferRadiatingShock"

[problem]
# available timesteppings: explicitEuler
timestepping = "explicitEuler"
# available distributions: Legendre, Hermite
distribution = [["Legendre"],[0.0]]
CFL = 0.9# 0.1
tEnd = 40.0

[moment_system]
# available closures: StochasticGalerkin, Euler, Euler2D, L2Filter, LassoFilter, RegularizedEuler, RadiationHydrodynamics, M1, ThermalRadiation
closure = "StochasticGalerkin"
moments = [["totalDegree"],[1]]
quadPoints = [["tensorizedGrid"],[2]]
#refinementThresholds = [0.1,0.001]
maxIterations = 1
epsilon = 1e-7
